### ISSUE TITLE
Error when running `npm start`

### ISSUE THREAD

**Issue by AnthonyOliveri** [IBM-Bluemix/get-started-node#8]
I followed the steps in the README to clone the repo and install the dependencies. When I run `npm start`, I get the following error log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@4.5.0
3 info using node@v7.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle get-started-node@0.1.1~prestart: get-started-node@0.1.1
6 silly lifecycle get-started-node@0.1.1~prestart: no script for prestart, continuing
7 info lifecycle get-started-node@0.1.1~start: get-started-node@0.1.1
8 verbose lifecycle get-started-node@0.1.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle get-started-node@0.1.1~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/anthony/Development/Test/get-started-node/node_modules/.bin:/Users/anthony/.swiftenv/shims:/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:/Users/anthony/Development/SDK/android-sdk-macosx/platform-tools/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin
10 verbose lifecycle get-started-node@0.1.1~start: CWD: /Users/anthony/Development/Test/get-started-node
11 silly lifecycle get-started-node@0.1.1~start: Args: [ '-c', 'node server.js' ]
12 silly lifecycle get-started-node@0.1.1~start: Returned: code: 1  signal: null
13 info lifecycle get-started-node@0.1.1~start: Failed to exec start script
14 verbose stack Error: get-started-node@0.1.1 start: `node server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid get-started-node@0.1.1
16 verbose cwd /Users/anthony/Development/Test/get-started-node
17 verbose Darwin 16.5.0
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 verbose node v7.10.0
20 verbose npm  v4.5.0
21 error code ELIFECYCLE
22 error errno 1
23 error get-started-node@0.1.1 start: `node server.js`
23 error Exit status 1
24 error Failed at the get-started-node@0.1.1 start script 'node server.js'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the get-started-node package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     node server.js
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs get-started-node
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls get-started-node
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

```

I updated node and npm versions to the latest, as suggested in the logs, but I got the same result.

**Comment by AnthonyOliveri** [comment]
Nevermind, this was my own issue. Turns out my machine was running something else on the port 3000.
